language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
 - gradle wrapper
 - chmod +x gradlew
 - git clone --depth=50 --branch=master git://github.com/jphp-compiler/jphp.git jphp

script: ./gradlew check
